"""create tables

Revision ID: 23702a146322
Revises: 
Create Date: 2023-07-13 18:03:42.399617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23702a146322'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uq_username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_username')
    )
    op.create_table('butterflies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('genus_species', sa.String(), nullable=False),
    sa.Column('conservation_status', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_butterflies_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('genus_species', sa.String(), nullable=False),
    sa.Column('growing_zone', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_plants_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('butterfly_tags',
    sa.Column('butterfly_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['butterfly_id'], ['butterflies.id'], name=op.f('fk_butterfly_tags_butterfly_id_butterflies')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_butterfly_tags_tag_id_tags')),
    sa.UniqueConstraint('butterfly_id', 'tag_id', name='_butterfly_id_tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('butterfly_tags')
    op.drop_table('plants')
    op.drop_table('butterflies')
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
