"""deleted admin column from User

Revision ID: 35e52896b33f
Revises: 2498b71dd7ff
Create Date: 2023-07-03 15:32:27.978665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35e52896b33f'
down_revision = '2498b71dd7ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
