"""added image to plant model

Revision ID: 49bea9c95b1f
Revises: 35e52896b33f
Create Date: 2023-07-04 15:14:34.370974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bea9c95b1f'
down_revision = '35e52896b33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('butterfly_tags', schema=None) as batch_op:
        batch_op.create_unique_constraint('_butterfly_id_tag_id', ['butterfly_id', 'tag_id'])

    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('butterfly_tags', schema=None) as batch_op:
        batch_op.drop_constraint('_butterfly_id_tag_id', type_='unique')

    # ### end Alembic commands ###
